### PR TITLE
Fix UTC offset issue

### LINKED ISSUE #1101: EventDate throws ArgumentOutOfRange exception on construction of AccountActivityEvent
""The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')"

I think what's happening is because in the constructor it's creating a new DateTime() and the default value is MinValue. Given I'm in UTC +10, it's taking taking 10 off the min value to convert to UTC, therefore it's less than 0. (A guess)
`    /// <summary>
    /// Twitter account event
    /// </summary>
    public class AccountActivityEvent
    {
        public AccountActivityEvent()
        {
            EventDate = new DateTime();
        }

        public long AccountUserId { get; set; }
        public DateTimeOffset EventDate { get; set; }
        public string Json { get; set; }
    }`

Changing the code to use `EventDate = DateTime.UtcNow;` removes the offset exception.

I'm not sure what the downstream effects may be?

### PR DESCRIPTION
**Pull request by piquet-h**
Fixes #1101

### CODE REVIEW

**Comment by piquet-h** [comment]
This also relates to a comment on #1030

**Comment by oferze** [comment]
Looks good, any chance for a merge soon?

**Comment by sphiecoh** [comment]
Hi there, any chance to merge this one ?

**Comment by oferze** [comment]
@linvi ?

**Comment by linvi** [comment]
Coming up. Sorry for that.

**Comment by linvi** [comment]
Tweetinvi 5.0.4 got released with the fix in it.

**Pull request merged**
