### PR TITLE
Proposed fix for #344 - combining Extended and Legacy entities

### PR DESCRIPTION
**Pull request by JoshKeegan**
Proposed fix for #344 - combining Extended and Legacy entities for Tweets received via the Streaming API.

Hi Linvi,
This isn't thoroughly tested so please don't merge, but I'm running this in my test environment and all is going well (for now!).

The idea is that properties on the root of a Tweet should be auto-populated (as you did), but only ever with one source of the data (legacy or extended) per entities type (Url, Media etc...). This is because combining them can lead to duplicate entities, but with slightly different indices (e.g. due to indices being [130, 150] on the extended tweet that would then be truncated to [130, 139] making the same entity appear different). The decision of which entities to use (when the streaming API gives both) will be made based on `TweetinviConfig.ApplicationSettings.TweetMode`.

I've also thrown in `ITweet.SafeDisplayTextRange` as a version of `ITweet.DisplayTextRange` that can be used without a null check.

And last but not least, a check for empty entities on retweets. When a retweet comes over the streaming API, it comes as a legacy tweet. For some extended tweets, this pushes an entity at the end to not showing up in the retweeted text. On the REST API the entity gets removed, but in the Streaming API things get funky with the start and end indices being the same and other properties coming null or empty strings. An example was Tweet ID 826091820153204737.

Can you comment on the `Distinct` calls? Are they there purely to remove the duplicates of combining legacy with extended entities, or does Twitter sometimes mess up and send duplicates?
Cheers,
Josh

### CODE REVIEW

**Comment by linvi** [comment]
I will review this.

Thanks

**Comment by JoshKeegan** [comment]
Removed WIP tag, as it's run overnight without error and the results all appear to be correct, so i'm now happy with this.

**Comment by JoshKeegan** [comment]
Added a bug fix (bug introduced in the first commit for this PR) for tweets with media fetched from the REST API.
If they had multiple media, only one was being used.

Also added a bunch of unit tests to cover that (all Tweets as received from the REST API) mostly to get my head around this, but they may as well stay :)

**Comment by JoshKeegan** [comment]
Another bug fix, this time for entities received over the streaming API (with unit tests).

This actually makes handling entities much simpler & re-reading bits of the docs I think this is what's supposed to happen.

All needs testing though, so expect more changes if it breaks on me tomorrow!

**Comment by linvi** [comment]
Thanks again, this was a great work.

**Pull request closed without merging**
