### PR TITLE
Fix #768 - Improve the way cross-cutting concerns are stored within the library

### LINKED ISSUE #768: PublishTweet no exception for "Invalid or expired token"
Hi,

Follow this code:

```C#
ITwitterCredentials credentials = Auth.SetUserCredentials(website.TwitterConsumerKey, website.TwitterConsumerSecret, authorizationKey, authorizationSecret);
ITweet theTweet = await TweetAsync.PublishTweet(message);
ITwitterException ex = ExceptionHandler.GetLastException();
```

With wrong credential (user has remove its authorization), PublishTweet return null.
**BUG:** ExceptionHandler.GetLastException(); return no exception !!!

But if I don't use Async:

```C#
ITwitterCredentials credentials = Auth.SetUserCredentials(website.TwitterConsumerKey, website.TwitterConsumerSecret, authorizationKey, authorizationSecret);
ITweet theTweet = Tweet.PublishTweet(message);
ITwitterException ex = ExceptionHandler.GetLastException();
```

With wrong credential (user has remove its authorization), PublishTweet return null.
And ex contain ""Unauthorized -  Authentication credentials were missing or incorrect.""
The behavior is OK.

Regards

### PR DESCRIPTION
**Pull request by JoshKeegan**
Updated description following numerous revisions to the original PR:

## Background
This PR aims to improve the way cross-cutting concerns, specifically:
 - Twitter credentials
 - Tweetinvi settings 
 - Exception Handling (i.e. swallowed exceptions)  

get stored. These values are stored specific to some context in order to simplify usage of the library (so that they don't need to be passed around to every Tweetinvi call). In order to work nicely in multi-threaded environments, this context is currently thread specific, however `async` and the common pattern `var result = await longAsyncMethod()` will not work nicely with any thread-specific context as `longAsyncMethod` could be executed in its own thread, therefore getting its own set of any thread specific variables.  

## New approach/Implementation details
These cross cutting concerns are now stored on the [`ExecutionContext`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.executioncontext?view=netframework-4.7.2) via [`AsyncLocal<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=netframework-4.7.2). Articles on these are pretty light, but the linked MSDN docs pretty good. The `ExecutionContext` is a .NET built-in (added alongside `async`) that allows for a context to be available between an asynchronous flow. I've put a *very* basic demo in this [gist](https://gist.github.com/JoshKeegan/66d649f6c5cc127d2f4057133d7d5bdc). 
Notes/gotchas important for its usage in Tweetinvi:
 - It's automatically shallow copied when a new `Task` is spawned
 - No copy-back when the child `Task` ends or is awaited  
 - Copying for a new `Task` can be blocked temporarily, giving a new task its own `ExecutionContext`
 - It can be shallow copied without a new `Task` being spawned, allowing for operations to be run with different cross-cutting concerns set (e.g. different credentials) without thread hopping.  

This means we must prepare the `ExecutionContext` before calling `Task.Run` by making sure any objects we want to have values propagated back up from a child thread have been instantiated. If they are instantiated, both threads will have references to the same object on the heap. If not, the new thread would make its own instance and the parent thread would make its own instance when they both first tried to access the context-specific object. Any object requiring this treatment should implement `ICrossExecutionContextPreparable`. Any time before spawning a new thread, the `ICrossExecutionContextPreparer` can be injected and its `Prepare` method can be called to ensure the Execution context is ready. For static methods (or externally from Tweetinvi - but there are much friendlier options for external use, see usage), this can be done by calling `Sync.PrepareForAsync()`.  
As we are now sharing objects between two threads, anything stored in `AsyncLocal<T>` (i.e. `T`) must be thread-safe.

## Usage
Most people will be able to continue using Tweetinvi as they previously have. Single threaded usage is unaffected.

### Async/await
Anyone using the `async` methods within Tweetinvi will now find that they behave as you would expect: sharing settings, propagating swallowed exceptions back up etc... without them needing to make any changes to their code. Anyone used to using `async` methods and `await` to handle long-running operations such as web requests should now find Tweetinvi quite natural. e.g.
```csharp
Auth.SetUserCredentials("1", "1", "1", "1");

// Request required data from Twitter in parallel
var taskUser = UserAsync.GetAuthenticatedUser();
var taskTrends = TrendsAsync.GetTrendsAt(woeId);

// Await results
var user = await taskUser;
var trends = await taskTrends;

// Combine results
return new Response()
{
  User = user,
  Trends = trends
};
```

### Using Synchronous Methods Asynchronously
If a method in Tweetinvi doesn't have an `async` version built in, the recommended way of running it asynchronously hasn't changed (although its implementation has). `Sync.ExecuteTaskAsync` should be used as it was in previous releases. Internally, `ITaskFactory.ExecuteTaskAsync` can be used.

### Independent tasks
Anyone using `Task.Run(...` or similar methods of starting threads running on the `ThreadPool` could be making use of the current thread specific context, e.g.:
```csharp
Auth.SetUserCredentials("1", "1", "1", "1");
Task t = Task.Run(() => 
{
  Auth.SetUserCredentials("2", "2", "2", "2");
  
  // Do things via Tweetinvi as user 2
});
// Do things via Tweetinvi as user 1...

await t;
```
This will no longer work, as the context storing the credentials is shared between the two threads. The recommended way of upgrading such code would be to use the new `Sync.ExecuteIsolatedTaskAsync` method in place of `Task.Run`, e.g.
```csharp
Auth.SetUserCredentials("1", "1", "1", "1");
ConfiguredTaskAwaitable t = Sync.ExecuteIsolatedTaskAsync(() => 
{
  Auth.SetUserCredentials("2", "2", "2", "2");
  
  // Do things via Tweetinvi as user 2
});
// Do things via Tweetinvi as user 1...

await t;
```
Which will be sufficient for most people.  
For anyone where a standard `Task.Run(action)` is insufficient and wants more control over the spawned task (e.g. to use a `CancellationToken`) can use `ExecutionContext.SuppressFlow` manually, e.g.
```csharp
Auth.SetUserCredentials("1", "1", "1", "1");
// Prevent execution context from being passed over to the new thread
Task t;
using (ExecutionContext.SuppressFlow())
{
  t = Task.Run(() =>
  {
    Auth.SetUserCredentials("2", "2", "2", "2");
    
    // Do things via Tweetinvi as user 2
  });
}
// Do things via Tweetinvi as user 1...

await t;
```
Where `Task.Run` could be replaced with any way of starting a `Task`, in .NET, giving you access to all options. You could also use the same concept if manually starting a `Thread`.  

Anyone spawning new worker threads from a master thread, where only workers use Tweetinvi will be unaffected, e.g.:
```csharp
// Get users to poll for
var users = await DbTwitterUsers.GetAllWithCredentials();

foreach(var user in users)
{
  Task.Run(() =>
  {
    pollHomeFeed(user);
  });
}

// Block forever, check for new users to poll for, or perform other non-Tweetinvi operations
```

## Additional notes
 - Upgraded to target .NET Standard 2.0. This was required for `ExecutionContext.SuppressFlow`. This change should have minimal impact as the version of .NET Framework required is the same as for .NET Standard 1.6, and I'd hope .NET Core users will be staying up to date :)
 - `AsyncEx` is no longer be required.
 - `IExceptionHandler` has new `TryPopException` and `TryPeekException` functions. 
 - Contents of `Developer Tools` dir haven't bee touched (but will need doing for a release due to the changes above).
 - New `ICredentialsRunner` has been split out from `ICredentialsAccessor` to prevent circular dependency caused by `CredentialsAccessor` now being `ICrossExecutionContextPreparable` and `CredentialsRunner` requiring `ICrossExecutionContextPreparer` to be injected (which in turn requires `ICrossExecutionContextPreparable[]` to be injected.

Many things have been left as thread-specific, as it appears this is just done to make objects not have to be thread safe. However, if other things should be on the `ExecutionContext` and specific to an async flow, let me know & I'll add them.

## Long term `async` impact
Using `Task.Run` for asynchronous IO operations is generally considered to be bad practice as even though you free up the calling thread, you are still hogging a thread from the thread pool to just sit waiting for an IO operation to complete.  
Long term it would be better if Tweetinvi could have its `async` methods calling `async` implementations of everything right down to the HTTP call. Behind the scenes, .NET should run this without needing to abuse the thread pool, as the IO operations will be waited on via IO completion ports, allowing for many IO operations to be awaited without ever spawning a new thread in the application.  

This change would be a substantial chunk of work, and the benefits wouldn't be noticed by most users who probably aren't sending anywhere near the volume of requests to Twitter to encounter scaling issues caused by juggling thousands of threads. However, I thought it still worth thinking about how *real* `async` could be offered in future, and making sure this PR didn't prevent it from being added.  

When an `async` method is entered, the `ExecutionContext` gets copied. As this is now where we are storing cross cutting concerns of the library, they must be set *before* entering an `async` method. This is why all of the methods in Tweetinvi that call `Sync.ExecuteTaskAsync` are not marked as `async` any more. They still return a `Task`, so can be awaited, but `async` is avoided in order to allow for the `ExecutionContext` to be prepared before it gets copied. The same would be true if ever *real* async methods were to be offered, so the public method won't be marked as `async` and must first prepare the `ExecutionContext` for copying, e.g.
```csharp
public static Task<bool> MuteUser(long userId)
{
    Sync.PrepareForAsync();
    return muteUser(userId);
}

private static async Task<bool> muteUser(long userId)
{
    return await Account.MuteUserAsync(userId).ConfigureAwait(false);
}
```
Or in this case since `muteUser()` doesn't do anything after the await, `MuteUser` could return `Account.MuteUserAsync` (which could be a *real* `async` method) directly, so long as the first thing it does is call `Sync.PrepareForAsync()`.  

So the changes in this PR would still be required for offering *real* `async` methods in the future (whilst still supporting exception swallowing etc...).

Update 02/01/2019: This is now being used in `Webhooks`, so see that for a real world example (even though the underlying `WebhooksController` will run synchronously, it has async method signatures).

### CODE REVIEW

**Comment by JoshKeegan** [comment]
Not ready yet.
Needs existing test suite running against (not run as not on windows & tests are in MSTest).

Could do with some manual testing, and ideally a few unit tests writing to cover this.

**Comment by JoshKeegan** [comment]
Existing test suite passes.
Could still do with some new tests to cover this though.

**Comment by linvi** [comment]
Will be reviewed, thanks @JoshKeegan

**Comment by JoshKeegan** [comment]
No probs!
Please don’t merge it just just yet though, i’d like to test it more first. I should get time later in the week :)

**Comment by JoshKeegan** [comment]
It's taken me longer than intended to get around to this, but I've added tests.
These highlighted problems with my proposed fix so I've made some changes :)

Instead of trying to move settings for the exception handler to the new thread (and exceptions back to the main one), I have changed the `IExceptionHandler` instance to be `AsyncLocal` rather than `ThreadLocal`/`ThreadStatic`. This means it will automatically be carried into the new task and can be used as normal. 

I can't think of any reason not to treat it like this, but feedback/comments would be welcomed!

This also raises the question of whether other places in Tweetinvi could be updated to work like this, to simplify `async` use e.g. preventing the need to copy settings when spawning a new task. The side-effect of doing this is that objects currently marked as `ThreadStatic` wouldn't necessarily need to be thread safe, but those marked as `AsyncLocal` must be.

**Comment by JoshKeegan** [comment]
Ready for review :)

**Comment by linvi** [comment]
Thanks josh, I will be reviewing.

**Comment by linvi** [comment]
Created another gist to show how the ThreadLocal and AsyncLocal differentiate and how references are being updated.

https://gist.github.com/linvi/142436ccdf5bb04f961ec699524817a4

**Comment by linvi** [comment]
I will be looking into it too but the following test is not passing at the moment :

``` c#
[TestMethod]
public async Task AsyncLocalPropertiesAreCarriedOutToChildAsync()
{
    // Arrange
    var creds = new TwitterCredentials();

    Auth.SetCredentials(creds);

    // Act
    await Sync.ExecuteTaskAsync(() =>
    {
        // Assert
        Assert.AreNotEqual(Auth.Credentials, creds);
        Assert.AreSame(Auth.Credentials, creds);
    });
}
```

**Comment by linvi** [comment]
This issue will be resolved by the Tweetinvi 5.0 which uses the concept of client and no longer ThreadStatics.

**Pull request closed without merging**
